---
homebrew_taps:
  - "cloudsmith-io/cloudsmith-cli"
  - "jesseduffield/lazydocker"
  - "jesseduffield/lazygit"
  - "warrensbox/tap"
  - "anomalyco/tap"
  - "nikitabobko/tap"

homebrew_packages:
  - "awscli"
  - "bash"
  - "bat"
  - "cloudsmith-cli"
  - "coreutils"
  - "diff-so-fancy"
  - "dive"
  - "eza"
  - "fastfetch"
  - "fd"
  - "ffmpeg"
  - "fish"
  - "fzf"
  - "gawk"
  - "gh"
  - "git"
  - "git-delta"
  - "git-lfs"
  - "helm"
  - "jq"
  - "jqp"
  - "just"
  - "kubecm"
  - "kubernetes-cli"
  - "lazydocker" 
  - "lazygit" 
  - "lua"
  - "luarocks"
  - "neovim"
  - "nushell"
  - "opencode"
  - "opentofu"
  - "pre-commit"
  - "presenterm"
  - "pyenv"
  - "rbenv"
  - "rclone"
  - "ripgrep"
  - "terraform-docs"
  - "tfswitch"
  - "uv"
  - "volta"
  - "wget"
  - "worktrunk"
  - "yazi"
  - "yq"
  - "zellij"
  - "zizmor"
  - "zlib"
  - "zoxide"

homebrew_casks:
  - "aerospace"
  - "betterdisplay"
  - "ghostty"
  - "iterm2"
  - "kitty"

