---
- name: Local machine setup
  hosts: localhost
  connection: local
  become: false

  roles:
    - common
    - role: macos
      when: ansible_facts['os_family'] == "Darwin"
    - role: arch
      when: ansible_facts['distribution'] == "Archlinux"
    - role: debian
      when: ansible_facts['os_family'] == "Debian"
